In [2]:
import tensorflow as tf
import numpy as np

a = tf.constant(10.0,shape=[2,5])
b = tf.reshape(a, [5,2])
c = tf.reduce_sum(b)
d = tf.constant(1.0, shape=[1,1])
init_ = tf.initialize_all_variables()

tf.Session().run(init_)
la = tf.Session().run(a)
lb = tf.Session().run(b)
lc = tf.Session().run(c)
ld = tf.Session().run(d)
print la, '\n', lb, '\n', lc, '\n', len(la[0])

[[ 10.  10.  10.  10.  10.]
 [ 10.  10.  10.  10.  10.]] 
[[ 10.  10.]
 [ 10.  10.]
 [ 10.  10.]
 [ 10.  10.]
 [ 10.  10.]] 
100.0 
5


In [1]:
!python -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 2

0.11.0rc2


In [8]:
a = tf.constant(10.0)

print tf.shape(a), tf.Session().run(a)

Tensor("Shape_3:0", shape=(0,), dtype=int32) 10.0
